### ISSUE TITLE
Wallaby.js not working for me

### ISSUE THREAD

**Issue by hmmlopez** [wallabyjs/ngCliWebpackSample#5]
I just created a new angular project using the angular-cli (see version below).
I'm trying to setup Wallaby.js for the first time so don't know much about the settings. 
I copied your configuration mentioned here (wallaby.js and the wallabyTest.ts) in the correct folders.
I'm using Visual Studio Code with the Wallaby.js extension.

I'm using version that came out yesterday:
```
angular-cli: 1.0.0-beta.24
node: 7.2.0
os: win32 x64
@angular/common: 2.4.0
@angular/compiler: 2.4.0
@angular/core: 2.4.0
@angular/forms: 2.4.0
@angular/http: 2.4.0
@angular/platform-browser: 2.4.0
@angular/platform-browser-dynamic: 2.4.0
@angular/router: 3.4.0
@angular/compiler-cli: 2.4.0
```

And getting the following error when I start the program (wallaby.js) in Visual Studio Code:
```
​​Error: Cannot find module 'undefined'​​
​​Error: Cannot find module 'undefined'​​
​​at http://localhost:56651/wallaby-webpack.js?1482330079487:1​​
​​Error​​
​​  at Compilation.<anonymous> (pathToProject\node_modules\webpack\lib\Compilation.js:364:28)​​
```

**Comment by FlemmingBehrend** [comment]
We have the same problem using IntelliJ. 

It was also introduced when updating angular to 2.4.0 and angular-cli to beta.24

**Comment by ArtemGovorov** [comment]
I have updated the `wallaby-webpack` package to throw a more descriptive error in future. The error in this case (with the upgrade to angular-cli to beta.24) is that the `angular2-template-loader` used in wallaby.js config for webpack is not supplied by angular-cli anymore, so all that is required to fix everything is to run:

```
npm i angular2-template-loader --save-dev
```

I have also updated the sample to include the package.

**Comment by hmmlopez** [comment]
Thanks, that solved it for me.

`npm install wallaby-webpack angular2-template-loader --save-dev`

I haven't tried it without the wallaby-webpack like you stated in your previous comment.
